### ISSUE TITLE
mock in test_appdirs.py

### ISSUE THREAD

**Issue by pgajdos** [cokelaer/easydev#20]
Would you please consider to make mock usage optional in favour of unittest.mock as in test_browse.py?

**Comment by cokelaer** [comment]
not an expert of mock / unittest.mock. What is the rationale behind this request ? thanks for the feedback.

**Comment by a-detiste** [comment]
Hi,

I should spend time to write down a `Python3-mock-removal` argumentation page: in short: since mock was merged into the standard library as unittest.mock; the original hasn't moved an itch and will stay there slowly bitrot. All project are switching to the maintained unittest.mock

https://wiki.debian.org/Python3-six-removal

![image](https://github.com/cokelaer/easydev/assets/7994192/878e0ca9-1546-44cd-9718-d13ab8590c77)

**Comment by pgajdos** [comment]
Thanks
